name: build
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: poetry setup
        run: python -m pip install -U poetry && poetry install
      - name: run the lint environment
        run: poetry run tox -e lint
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        # windows/osx builds much more expensive; try to limit these
        include:
          - os: windows-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.10"
    name: "test: python${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: poetry setup
        run: python -m pip install -U poetry && poetry install
      - name: run tests
        run: poetry run python -m tox
